version: '3.8'

services:
  db:
    image: postgres:15
    container_name: opais_340b_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: opais_340b
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - opais_340b_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d opais_340b"]
      interval: 10s
      timeout: 5s
      retries: 5

  loader:
    build: .
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
      - ./data/raw:/app/data/raw:ro  # Read-only mount for data
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/opais_340b

volumes:
  opais_340b_data:
    name: opais_340b_data  # Named volume for persistence between container restarts